// ignore_for_file: type=lint

// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by tool/figma_variables_converter/figma_variables_converter.dart'

part of 'colors.dart';

mixin _LightModeColorsMixin on AppColors {
  @override
  AppColor get backgroundAccentPrimary => AppColor._color(
    0xFF414552,
    name: 'backgroundAccentPrimary',
    designName: 'Bg/Accent/Primary',
  );

  @override
  AppColor get backgroundAccentPrimaryHover => AppColor._color(
    0xFF31343E,
    name: 'backgroundAccentPrimaryHover',
    designName: 'Bg/Accent/Primary (hover)',
  );

  @override
  AppColor get backgroundAccentPrimaryPressed => AppColor._color(
    0xFF292B34,
    name: 'backgroundAccentPrimaryPressed',
    designName: 'Bg/Accent/Primary (pressed)',
  );

  @override
  AppColor get backgroundAccentSecondary => AppColor._color(
    0xFF979AA4,
    name: 'backgroundAccentSecondary',
    designName: 'Bg/Accent/Secondary',
  );

  @override
  AppColor get backgroundAccentSecondaryHover => AppColor._color(
    0xFF858995,
    name: 'backgroundAccentSecondaryHover',
    designName: 'Bg/Accent/Secondary (hover)',
  );

  @override
  AppColor get backgroundAccentSecondaryPressed => AppColor._color(
    0xFF626776,
    name: 'backgroundAccentSecondaryPressed',
    designName: 'Bg/Accent/Secondary (pressed)',
  );

  @override
  AppColor get backgroundAccentTertiary => AppColor._color(
    0xFFF7F7F8,
    name: 'backgroundAccentTertiary',
    designName: 'Bg/Accent/Tertiary',
  );

  @override
  AppColor get backgroundAccentTertiaryHover => AppColor._color(
    0xFFEEEEF0,
    name: 'backgroundAccentTertiaryHover',
    designName: 'Bg/Accent/Tertiary (hover)',
  );

  @override
  AppColor get backgroundAccentTertiaryPressed => AppColor._color(
    0xFFDCDDE1,
    name: 'backgroundAccentTertiaryPressed',
    designName: 'Bg/Accent/Tertiary (pressed)',
  );

  @override
  AppColor get backgroundActivePrimary => AppColor._color(
    0xFF414552,
    name: 'backgroundActivePrimary',
    designName: 'Bg/Active/Primary',
  );

  @override
  AppColor get backgroundActivePrimaryHover => AppColor._color(
    0xFF31343E,
    name: 'backgroundActivePrimaryHover',
    designName: 'Bg/Active/Primary (hover)',
  );

  @override
  AppColor get backgroundActivePrimaryPressed => AppColor._color(
    0xFF292B34,
    name: 'backgroundActivePrimaryPressed',
    designName: 'Bg/Active/Primary (pressed)',
  );

  @override
  AppColor get backgroundActiveSecondary => AppColor._color(
    0xFF979AA4,
    name: 'backgroundActiveSecondary',
    designName: 'Bg/Active/Secondary',
  );

  @override
  AppColor get backgroundActiveSecondaryHover => AppColor._color(
    0xFF858995,
    name: 'backgroundActiveSecondaryHover',
    designName: 'Bg/Active/Secondary (hover)',
  );

  @override
  AppColor get backgroundActiveSecondaryPressed => AppColor._color(
    0xFF626776,
    name: 'backgroundActiveSecondaryPressed',
    designName: 'Bg/Active/Secondary (pressed)',
  );

  @override
  AppColor get backgroundActiveTertiary => AppColor._color(
    0xFFF7F7F8,
    name: 'backgroundActiveTertiary',
    designName: 'Bg/Active/Tertiary',
  );

  @override
  AppColor get backgroundActiveTertiaryHover => AppColor._color(
    0xFFEEEEF0,
    name: 'backgroundActiveTertiaryHover',
    designName: 'Bg/Active/Tertiary (hover)',
  );

  @override
  AppColor get backgroundActiveTertiaryPressed => AppColor._color(
    0xFFDCDDE1,
    name: 'backgroundActiveTertiaryPressed',
    designName: 'Bg/Active/Tertiary (pressed)',
  );

  @override
  AppColor get backgroundDangerPrimary => AppColor._color(
    0xFFC12C2C,
    name: 'backgroundDangerPrimary',
    designName: 'Bg/Danger/Primary',
  );

  @override
  AppColor get backgroundDangerPrimaryHover => AppColor._color(
    0xFFB91E1E,
    name: 'backgroundDangerPrimaryHover',
    designName: 'Bg/Danger/Primary (hover)',
  );

  @override
  AppColor get backgroundDangerPrimaryPressed => AppColor._color(
    0xFF901717,
    name: 'backgroundDangerPrimaryPressed',
    designName: 'Bg/Danger/Primary (pressed)',
  );

  @override
  AppColor get backgroundDangerSecondary => AppColor._color(
    0xFFE69090,
    name: 'backgroundDangerSecondary',
    designName: 'Bg/Danger/Secondary',
  );

  @override
  AppColor get backgroundDangerSecondaryHover => AppColor._color(
    0xFFE17A7A,
    name: 'backgroundDangerSecondaryHover',
    designName: 'Bg/Danger/Secondary (hover)',
  );

  @override
  AppColor get backgroundDangerSecondaryPressed => AppColor._color(
    0xFFDC6464,
    name: 'backgroundDangerSecondaryPressed',
    designName: 'Bg/Danger/Secondary (pressed)',
  );

  @override
  AppColor get backgroundDangerTertiary => AppColor._color(
    0xFFFAE9E9,
    name: 'backgroundDangerTertiary',
    designName: 'Bg/Danger/Tertiary',
  );

  @override
  AppColor get backgroundDangerTertiaryHover => AppColor._color(
    0xFFF5D3D3,
    name: 'backgroundDangerTertiaryHover',
    designName: 'Bg/Danger/Tertiary (hover)',
  );

  @override
  AppColor get backgroundDangerTertiaryPressed => AppColor._color(
    0xFFEFB8B8,
    name: 'backgroundDangerTertiaryPressed',
    designName: 'Bg/Danger/Tertiary (pressed)',
  );

  @override
  AppColor get backgroundDefaultPrimary => AppColor._color(
    0xFFFFFFFF,
    name: 'backgroundDefaultPrimary',
    designName: 'Bg/Default/Primary',
  );

  @override
  AppColor get backgroundDefaultPrimaryHover => AppColor._color(
    0xFFF9F9FF,
    name: 'backgroundDefaultPrimaryHover',
    designName: 'Bg/Default/Primary (hover)',
  );

  @override
  AppColor get backgroundDefaultPrimaryPressed => AppColor._color(
    0xFFF0F2FA,
    name: 'backgroundDefaultPrimaryPressed',
    designName: 'Bg/Default/Primary (pressed)',
  );

  @override
  AppColor get backgroundDefaultScrim => AppColor._color(
    0x33040E29,
    name: 'backgroundDefaultScrim',
    designName: 'Bg/Default/Scrim',
  );

  @override
  AppColor get backgroundDefaultSecondary => AppColor._color(
    0xFFF9F9FF,
    name: 'backgroundDefaultSecondary',
    designName: 'Bg/Default/Secondary',
  );

  @override
  AppColor get backgroundDefaultSecondaryHover => AppColor._color(
    0xFFF0F2FA,
    name: 'backgroundDefaultSecondaryHover',
    designName: 'Bg/Default/Secondary (hover)',
  );

  @override
  AppColor get backgroundDefaultSecondaryPressed => AppColor._color(
    0xFFE1E1EB,
    name: 'backgroundDefaultSecondaryPressed',
    designName: 'Bg/Default/Secondary (pressed)',
  );

  @override
  AppColor get backgroundDefaultTertiary => AppColor._color(
    0xFFE1E1EB,
    name: 'backgroundDefaultTertiary',
    designName: 'Bg/Default/Tertiary',
  );

  @override
  AppColor get backgroundDefaultTertiaryHover => AppColor._color(
    0xFFCECEDB,
    name: 'backgroundDefaultTertiaryHover',
    designName: 'Bg/Default/Tertiary (hover)',
  );

  @override
  AppColor get backgroundDefaultTertiaryPressed => AppColor._color(
    0xFFA3A3B3,
    name: 'backgroundDefaultTertiaryPressed',
    designName: 'Bg/Default/Tertiary (pressed)',
  );

  @override
  AppColor get backgroundDisabledPrimary => AppColor._color(
    0xFFE1E1EB,
    name: 'backgroundDisabledPrimary',
    designName: 'Bg/Disabled/Primary',
  );

  @override
  AppColor get backgroundDisabledSecondary => AppColor._color(
    0xFFF0F2FA,
    name: 'backgroundDisabledSecondary',
    designName: 'Bg/Disabled/Secondary',
  );

  @override
  AppColor get backgroundDisabledTertiary => AppColor._color(
    0xFFF9F9FF,
    name: 'backgroundDisabledTertiary',
    designName: 'Bg/Disabled/Tertiary',
  );

  @override
  AppColor get backgroundInfoPrimary => AppColor._color(
    0xFF1668DB,
    name: 'backgroundInfoPrimary',
    designName: 'Bg/Info/Primary',
  );

  @override
  AppColor get backgroundInfoPrimaryHover => AppColor._color(
    0xFF145EC5,
    name: 'backgroundInfoPrimaryHover',
    designName: 'Bg/Info/Primary (hover)',
  );

  @override
  AppColor get backgroundInfoPrimaryPressed => AppColor._color(
    0xFF1253AF,
    name: 'backgroundInfoPrimaryPressed',
    designName: 'Bg/Info/Primary (pressed)',
  );

  @override
  AppColor get backgroundInfoSecondary => AppColor._color(
    0xFF8BB4ED,
    name: 'backgroundInfoSecondary',
    designName: 'Bg/Info/Secondary',
  );

  @override
  AppColor get backgroundInfoSecondaryHover => AppColor._color(
    0xFF5C95E6,
    name: 'backgroundInfoSecondaryHover',
    designName: 'Bg/Info/Secondary (hover)',
  );

  @override
  AppColor get backgroundInfoSecondaryPressed => AppColor._color(
    0xFF4586E2,
    name: 'backgroundInfoSecondaryPressed',
    designName: 'Bg/Info/Secondary (pressed)',
  );

  @override
  AppColor get backgroundInfoTertiary => AppColor._color(
    0xFFE8F0FB,
    name: 'backgroundInfoTertiary',
    designName: 'Bg/Info/Tertiary',
  );

  @override
  AppColor get backgroundInfoTertiaryHover => AppColor._color(
    0xFFD0E1F8,
    name: 'backgroundInfoTertiaryHover',
    designName: 'Bg/Info/Tertiary (hover)',
  );

  @override
  AppColor get backgroundInfoTertiaryPressed => AppColor._color(
    0xFFB9D2F4,
    name: 'backgroundInfoTertiaryPressed',
    designName: 'Bg/Info/Tertiary (pressed)',
  );

  @override
  AppColor get backgroundInversePrimary => AppColor._color(
    0xFF18181D,
    name: 'backgroundInversePrimary',
    designName: 'Bg/Inverse/Primary',
  );

  @override
  AppColor get backgroundInversePrimaryHover => AppColor._color(
    0xFF2F2F39,
    name: 'backgroundInversePrimaryHover',
    designName: 'Bg/Inverse/Primary (hover)',
  );

  @override
  AppColor get backgroundInversePrimaryPressed => AppColor._color(
    0xFF3F3F4D,
    name: 'backgroundInversePrimaryPressed',
    designName: 'Bg/Inverse/Primary (pressed)',
  );

  @override
  AppColor get backgroundMapBarBadge => AppColor._color(
    0xFFFAE6F1,
    name: 'backgroundMapBarBadge',
    designName: 'Bg/Map/Bar badge',
  );

  @override
  AppColor get backgroundMapBarPin => AppColor._color(
    0xFFC41475,
    name: 'backgroundMapBarPin',
    designName: 'Bg/Map/Bar pin',
  );

  @override
  AppColor get backgroundMapCulturalBadge => AppColor._color(
    0xFFF5EEE6,
    name: 'backgroundMapCulturalBadge',
    designName: 'Bg/Map/Cultural badge',
  );

  @override
  AppColor get backgroundMapCulturalPin => AppColor._color(
    0xFF8E4A00,
    name: 'backgroundMapCulturalPin',
    designName: 'Bg/Map/Cultural pin',
  );

  @override
  AppColor get backgroundMapFoodBadge => AppColor._color(
    0xFFFAE6F1,
    name: 'backgroundMapFoodBadge',
    designName: 'Bg/Map/Food badge',
  );

  @override
  AppColor get backgroundMapFoodPin => AppColor._color(
    0xFFC41475,
    name: 'backgroundMapFoodPin',
    designName: 'Bg/Map/Food pin',
  );

  @override
  AppColor get backgroundMapLeancodeBadge => AppColor._color(
    0xFFF7F7F8,
    name: 'backgroundMapLeancodeBadge',
    designName: 'Bg/Map/LeanCode badge',
  );

  @override
  AppColor get backgroundMapLeancodePin => AppColor._color(
    0xFF515667,
    name: 'backgroundMapLeancodePin',
    designName: 'Bg/Map/LeanCode pin',
  );

  @override
  AppColor get backgroundMapMainEventBadge => AppColor._color(
    0xFFE8F0FB,
    name: 'backgroundMapMainEventBadge',
    designName: 'Bg/Map/Main event badge',
  );

  @override
  AppColor get backgroundMapMainEventPin => AppColor._color(
    0xFF145EC5,
    name: 'backgroundMapMainEventPin',
    designName: 'Bg/Map/Main event pin',
  );

  @override
  AppColor get backgroundMapMuseumBadge => AppColor._color(
    0xFFE8F0FB,
    name: 'backgroundMapMuseumBadge',
    designName: 'Bg/Map/Museum badge',
  );

  @override
  AppColor get backgroundMapMuseumPin => AppColor._color(
    0xFF145EC5,
    name: 'backgroundMapMuseumPin',
    designName: 'Bg/Map/Museum pin',
  );

  @override
  AppColor get backgroundMapOtherBadge => AppColor._color(
    0xFFF7F7F8,
    name: 'backgroundMapOtherBadge',
    designName: 'Bg/Map/Other badge',
  );

  @override
  AppColor get backgroundMapOtherPin => AppColor._color(
    0xFF515667,
    name: 'backgroundMapOtherPin',
    designName: 'Bg/Map/Other pin',
  );

  @override
  AppColor get backgroundMapParkBadge => AppColor._color(
    0xFFE7F3ED,
    name: 'backgroundMapParkBadge',
    designName: 'Bg/Map/Park badge',
  );

  @override
  AppColor get backgroundMapParkPin => AppColor._color(
    0xFF0C7540,
    name: 'backgroundMapParkPin',
    designName: 'Bg/Map/Park pin',
  );

  @override
  AppColor get backgroundMapSideEventBadge => AppColor._color(
    0xFFF7E6FA,
    name: 'backgroundMapSideEventBadge',
    designName: 'Bg/Map/Side event badge',
  );

  @override
  AppColor get backgroundMapSideEventPin => AppColor._color(
    0xFFAA14C4,
    name: 'backgroundMapSideEventPin',
    designName: 'Bg/Map/Side event pin',
  );

  @override
  AppColor get backgroundSuccessPrimary => AppColor._color(
    0xFF0D8247,
    name: 'backgroundSuccessPrimary',
    designName: 'Bg/Success/Primary',
  );

  @override
  AppColor get backgroundSuccessPrimaryHover => AppColor._color(
    0xFF0C7540,
    name: 'backgroundSuccessPrimaryHover',
    designName: 'Bg/Success/Primary (hover)',
  );

  @override
  AppColor get backgroundSuccessPrimaryPressed => AppColor._color(
    0xFF095B32,
    name: 'backgroundSuccessPrimaryPressed',
    designName: 'Bg/Success/Primary (pressed)',
  );

  @override
  AppColor get backgroundSuccessSecondary => AppColor._color(
    0xFFB6DAC8,
    name: 'backgroundSuccessSecondary',
    designName: 'Bg/Success/Secondary',
  );

  @override
  AppColor get backgroundSuccessSecondaryHover => AppColor._color(
    0xFF9ECDB5,
    name: 'backgroundSuccessSecondaryHover',
    designName: 'Bg/Success/Secondary (hover)',
  );

  @override
  AppColor get backgroundSuccessSecondaryPressed => AppColor._color(
    0xFF6EB491,
    name: 'backgroundSuccessSecondaryPressed',
    designName: 'Bg/Success/Secondary (pressed)',
  );

  @override
  AppColor get backgroundSuccessTertiary => AppColor._color(
    0xFFE7F3ED,
    name: 'backgroundSuccessTertiary',
    designName: 'Bg/Success/Tertiary',
  );

  @override
  AppColor get backgroundSuccessTertiaryHover => AppColor._color(
    0xFFCFE6DA,
    name: 'backgroundSuccessTertiaryHover',
    designName: 'Bg/Success/Tertiary (hover)',
  );

  @override
  AppColor get backgroundSuccessTertiaryPressed => AppColor._color(
    0xFFCFE6DA,
    name: 'backgroundSuccessTertiaryPressed',
    designName: 'Bg/Success/Tertiary (pressed)',
  );

  @override
  AppColor get backgroundWarningPrimary => AppColor._color(
    0xFF9E5200,
    name: 'backgroundWarningPrimary',
    designName: 'Bg/Warning/Primary',
  );

  @override
  AppColor get backgroundWarningPrimaryHover => AppColor._color(
    0xFF8E4A00,
    name: 'backgroundWarningPrimaryHover',
    designName: 'Bg/Warning/Primary (hover)',
  );

  @override
  AppColor get backgroundWarningPrimaryPressed => AppColor._color(
    0xFF6F3900,
    name: 'backgroundWarningPrimaryPressed',
    designName: 'Bg/Warning/Primary (pressed)',
  );

  @override
  AppColor get backgroundWarningSecondary => AppColor._color(
    0xFFD8BA99,
    name: 'backgroundWarningSecondary',
    designName: 'Bg/Warning/Secondary',
  );

  @override
  AppColor get backgroundWarningSecondaryHover => AppColor._color(
    0xFFCFA980,
    name: 'backgroundWarningSecondaryHover',
    designName: 'Bg/Warning/Secondary (hover)',
  );

  @override
  AppColor get backgroundWarningSecondaryPressed => AppColor._color(
    0xFFC59766,
    name: 'backgroundWarningSecondaryPressed',
    designName: 'Bg/Warning/Secondary (pressed)',
  );

  @override
  AppColor get backgroundWarningTertiary => AppColor._color(
    0xFFF5EEE6,
    name: 'backgroundWarningTertiary',
    designName: 'Bg/Warning/Tertiary',
  );

  @override
  AppColor get backgroundWarningTertiaryHover => AppColor._color(
    0xFFECDCCC,
    name: 'backgroundWarningTertiaryHover',
    designName: 'Bg/Warning/Tertiary (hover)',
  );

  @override
  AppColor get backgroundWarningTertiaryPressed => AppColor._color(
    0xFFE2CBB3,
    name: 'backgroundWarningTertiaryPressed',
    designName: 'Bg/Warning/Tertiary (pressed)',
  );

  @override
  AppColor get foregroundAccentPrimary => AppColor._color(
    0xFF414552,
    name: 'foregroundAccentPrimary',
    designName: 'Fg/Accent/Primary',
  );

  @override
  AppColor get foregroundAccentPrimaryHover => AppColor._color(
    0xFF31343E,
    name: 'foregroundAccentPrimaryHover',
    designName: 'Fg/Accent/Primary (hover)',
  );

  @override
  AppColor get foregroundAccentPrimaryPressed => AppColor._color(
    0xFF292B34,
    name: 'foregroundAccentPrimaryPressed',
    designName: 'Fg/Accent/Primary (pressed)',
  );

  @override
  AppColor get foregroundAccentQuaternary => AppColor._color(
    0xFFCBCCD1,
    name: 'foregroundAccentQuaternary',
    designName: 'Fg/Accent/Quaternary',
  );

  @override
  AppColor get foregroundAccentSecondary => AppColor._color(
    0xFF515667,
    name: 'foregroundAccentSecondary',
    designName: 'Fg/Accent/Secondary',
  );

  @override
  AppColor get foregroundAccentSecondaryHover => AppColor._color(
    0xFF414552,
    name: 'foregroundAccentSecondaryHover',
    designName: 'Fg/Accent/Secondary (hover)',
  );

  @override
  AppColor get foregroundAccentSecondaryPressed => AppColor._color(
    0xFF31343E,
    name: 'foregroundAccentSecondaryPressed',
    designName: 'Fg/Accent/Secondary (pressed)',
  );

  @override
  AppColor get foregroundAccentTertiary => AppColor._color(
    0xFF626776,
    name: 'foregroundAccentTertiary',
    designName: 'Fg/Accent/Tertiary',
  );

  @override
  AppColor get foregroundActivePrimary => AppColor._color(
    0xFF414552,
    name: 'foregroundActivePrimary',
    designName: 'Fg/Active/Primary',
  );

  @override
  AppColor get foregroundActivePrimaryHover => AppColor._color(
    0xFF31343E,
    name: 'foregroundActivePrimaryHover',
    designName: 'Fg/Active/Primary (hover)',
  );

  @override
  AppColor get foregroundActivePrimaryPressed => AppColor._color(
    0xFF292B34,
    name: 'foregroundActivePrimaryPressed',
    designName: 'Fg/Active/Primary (pressed)',
  );

  @override
  AppColor get foregroundActiveQuaternary => AppColor._color(
    0xFFCBCCD1,
    name: 'foregroundActiveQuaternary',
    designName: 'Fg/Active/Quaternary',
  );

  @override
  AppColor get foregroundActiveSecondary => AppColor._color(
    0xFF515667,
    name: 'foregroundActiveSecondary',
    designName: 'Fg/Active/Secondary',
  );

  @override
  AppColor get foregroundActiveSecondaryHover => AppColor._color(
    0xFF414552,
    name: 'foregroundActiveSecondaryHover',
    designName: 'Fg/Active/Secondary (hover)',
  );

  @override
  AppColor get foregroundActiveSecondaryPressed => AppColor._color(
    0xFF31343E,
    name: 'foregroundActiveSecondaryPressed',
    designName: 'Fg/Active/Secondary (pressed)',
  );

  @override
  AppColor get foregroundActiveTertiary => AppColor._color(
    0xFF626776,
    name: 'foregroundActiveTertiary',
    designName: 'Fg/Active/Tertiary',
  );

  @override
  AppColor get foregroundDangerPrimary => AppColor._color(
    0xFFC12C2C,
    name: 'foregroundDangerPrimary',
    designName: 'Fg/Danger/Primary',
  );

  @override
  AppColor get foregroundDangerPrimaryHover => AppColor._color(
    0xFFB91E1E,
    name: 'foregroundDangerPrimaryHover',
    designName: 'Fg/Danger/Primary (hover)',
  );

  @override
  AppColor get foregroundDangerPrimaryPressed => AppColor._color(
    0xFF901717,
    name: 'foregroundDangerPrimaryPressed',
    designName: 'Fg/Danger/Primary (pressed)',
  );

  @override
  AppColor get foregroundDangerQuaternary => AppColor._color(
    0xFFEFB8B8,
    name: 'foregroundDangerQuaternary',
    designName: 'Fg/Danger/Quaternary',
  );

  @override
  AppColor get foregroundDangerSecondary => AppColor._color(
    0xFFDC6464,
    name: 'foregroundDangerSecondary',
    designName: 'Fg/Danger/Secondary',
  );

  @override
  AppColor get foregroundDangerSecondaryHover => AppColor._color(
    0xFFD44343,
    name: 'foregroundDangerSecondaryHover',
    designName: 'Fg/Danger/Secondary (hover)',
  );

  @override
  AppColor get foregroundDangerSecondaryPressed => AppColor._color(
    0xFFC12C2C,
    name: 'foregroundDangerSecondaryPressed',
    designName: 'Fg/Danger/Secondary (pressed)',
  );

  @override
  AppColor get foregroundDangerTertiary => AppColor._color(
    0xFFE69090,
    name: 'foregroundDangerTertiary',
    designName: 'Fg/Danger/Tertiary',
  );

  @override
  AppColor get foregroundDefaultPrimary => AppColor._color(
    0xFF18181D,
    name: 'foregroundDefaultPrimary',
    designName: 'Fg/Default/Primary',
  );

  @override
  AppColor get foregroundDefaultPrimaryHover => AppColor._color(
    0xFF282830,
    name: 'foregroundDefaultPrimaryHover',
    designName: 'Fg/Default/Primary (hover)',
  );

  @override
  AppColor get foregroundDefaultPrimaryPressed => AppColor._color(
    0xFF2F2F39,
    name: 'foregroundDefaultPrimaryPressed',
    designName: 'Fg/Default/Primary (pressed)',
  );

  @override
  AppColor get foregroundDefaultQuaternary => AppColor._color(
    0xFFCECEDB,
    name: 'foregroundDefaultQuaternary',
    designName: 'Fg/Default/Quaternary',
  );

  @override
  AppColor get foregroundDefaultSecondary => AppColor._color(
    0xFF606071,
    name: 'foregroundDefaultSecondary',
    designName: 'Fg/Default/Secondary',
  );

  @override
  AppColor get foregroundDefaultSecondaryHover => AppColor._color(
    0xFF4F4F60,
    name: 'foregroundDefaultSecondaryHover',
    designName: 'Fg/Default/Secondary (hover)',
  );

  @override
  AppColor get foregroundDefaultSecondaryPressed => AppColor._color(
    0xFF3F3F4D,
    name: 'foregroundDefaultSecondaryPressed',
    designName: 'Fg/Default/Secondary (pressed)',
  );

  @override
  AppColor get foregroundDefaultTertiary => AppColor._color(
    0xFF808093,
    name: 'foregroundDefaultTertiary',
    designName: 'Fg/Default/Tertiary',
  );

  @override
  AppColor get foregroundDisabledPrimary => AppColor._color(
    0xFF808093,
    name: 'foregroundDisabledPrimary',
    designName: 'Fg/Disabled/Primary',
  );

  @override
  AppColor get foregroundDisabledSecondary => AppColor._color(
    0xFFA3A3B3,
    name: 'foregroundDisabledSecondary',
    designName: 'Fg/Disabled/Secondary',
  );

  @override
  AppColor get foregroundDisabledTertiary => AppColor._color(
    0xFFCECEDB,
    name: 'foregroundDisabledTertiary',
    designName: 'Fg/Disabled/Tertiary',
  );

  @override
  AppColor get foregroundInfoPrimary => AppColor._color(
    0xFF1668DB,
    name: 'foregroundInfoPrimary',
    designName: 'Fg/Info/Primary',
  );

  @override
  AppColor get foregroundInfoPrimaryHover => AppColor._color(
    0xFF145EC5,
    name: 'foregroundInfoPrimaryHover',
    designName: 'Fg/Info/Primary (hover)',
  );

  @override
  AppColor get foregroundInfoPrimaryPressed => AppColor._color(
    0xFF1253AF,
    name: 'foregroundInfoPrimaryPressed',
    designName: 'Fg/Info/Primary (pressed)',
  );

  @override
  AppColor get foregroundInfoQuaternary => AppColor._color(
    0xFFB9D2F4,
    name: 'foregroundInfoQuaternary',
    designName: 'Fg/Info/Quaternary',
  );

  @override
  AppColor get foregroundInfoSecondary => AppColor._color(
    0xFF4586E2,
    name: 'foregroundInfoSecondary',
    designName: 'Fg/Info/Secondary',
  );

  @override
  AppColor get foregroundInfoSecondaryHover => AppColor._color(
    0xFF2D77DF,
    name: 'foregroundInfoSecondaryHover',
    designName: 'Fg/Info/Secondary (hover)',
  );

  @override
  AppColor get foregroundInfoSecondaryPressed => AppColor._color(
    0xFF1668DB,
    name: 'foregroundInfoSecondaryPressed',
    designName: 'Fg/Info/Secondary (pressed)',
  );

  @override
  AppColor get foregroundInfoTertiary => AppColor._color(
    0xFF8BB4ED,
    name: 'foregroundInfoTertiary',
    designName: 'Fg/Info/Tertiary',
  );

  @override
  AppColor get foregroundInversePrimary => AppColor._color(
    0xFFF9F9FF,
    name: 'foregroundInversePrimary',
    designName: 'Fg/Inverse/Primary',
  );

  @override
  AppColor get foregroundInversePrimaryHover => AppColor._color(
    0xFFF0F2FA,
    name: 'foregroundInversePrimaryHover',
    designName: 'Fg/Inverse/Primary (hover)',
  );

  @override
  AppColor get foregroundInversePrimaryPressed => AppColor._color(
    0xFFE1E1EB,
    name: 'foregroundInversePrimaryPressed',
    designName: 'Fg/Inverse/Primary (pressed)',
  );

  @override
  AppColor get foregroundMapBar => AppColor._color(
    0xFFAF1268,
    name: 'foregroundMapBar',
    designName: 'Fg/Map/Bar',
  );

  @override
  AppColor get foregroundMapCultural => AppColor._color(
    0xFF6F3900,
    name: 'foregroundMapCultural',
    designName: 'Fg/Map/Cultural',
  );

  @override
  AppColor get foregroundMapFood => AppColor._color(
    0xFFAF1268,
    name: 'foregroundMapFood',
    designName: 'Fg/Map/Food',
  );

  @override
  AppColor get foregroundMapLeancode => AppColor._color(
    0xFF414552,
    name: 'foregroundMapLeancode',
    designName: 'Fg/Map/LeanCode',
  );

  @override
  AppColor get foregroundMapMainEvent => AppColor._color(
    0xFF1253AF,
    name: 'foregroundMapMainEvent',
    designName: 'Fg/Map/Main event',
  );

  @override
  AppColor get foregroundMapMuseum => AppColor._color(
    0xFF1253AF,
    name: 'foregroundMapMuseum',
    designName: 'Fg/Map/Museum',
  );

  @override
  AppColor get foregroundMapOther => AppColor._color(
    0xFF414552,
    name: 'foregroundMapOther',
    designName: 'Fg/Map/Other',
  );

  @override
  AppColor get foregroundMapPark => AppColor._color(
    0xFF095B32,
    name: 'foregroundMapPark',
    designName: 'Fg/Map/Park',
  );

  @override
  AppColor get foregroundMapSideEvent => AppColor._color(
    0xFF9712AF,
    name: 'foregroundMapSideEvent',
    designName: 'Fg/Map/Side event',
  );

  @override
  AppColor get foregroundSuccessPrimary => AppColor._color(
    0xFF0D8247,
    name: 'foregroundSuccessPrimary',
    designName: 'Fg/Success/Primary',
  );

  @override
  AppColor get foregroundSuccessPrimaryHover => AppColor._color(
    0xFF0C7540,
    name: 'foregroundSuccessPrimaryHover',
    designName: 'Fg/Success/Primary (hover)',
  );

  @override
  AppColor get foregroundSuccessPrimaryPressed => AppColor._color(
    0xFF095B32,
    name: 'foregroundSuccessPrimaryPressed',
    designName: 'Fg/Success/Primary (pressed)',
  );

  @override
  AppColor get foregroundSuccessQuaternary => AppColor._color(
    0xFFCFE6DA,
    name: 'foregroundSuccessQuaternary',
    designName: 'Fg/Success/Quaternary',
  );

  @override
  AppColor get foregroundSuccessSecondary => AppColor._color(
    0xFF6EB491,
    name: 'foregroundSuccessSecondary',
    designName: 'Fg/Success/Secondary',
  );

  @override
  AppColor get foregroundSuccessSecondaryHover => AppColor._color(
    0xFF3D9B6C,
    name: 'foregroundSuccessSecondaryHover',
    designName: 'Fg/Success/Secondary (hover)',
  );

  @override
  AppColor get foregroundSuccessSecondaryPressed => AppColor._color(
    0xFF0D8247,
    name: 'foregroundSuccessSecondaryPressed',
    designName: 'Fg/Success/Secondary (pressed)',
  );

  @override
  AppColor get foregroundSuccessTertiary => AppColor._color(
    0xFFB6DAC8,
    name: 'foregroundSuccessTertiary',
    designName: 'Fg/Success/Tertiary',
  );

  @override
  AppColor get foregroundWarningPrimary => AppColor._color(
    0xFF9E5200,
    name: 'foregroundWarningPrimary',
    designName: 'Fg/Warning/Primary',
  );

  @override
  AppColor get foregroundWarningPrimaryHover => AppColor._color(
    0xFF8E4A00,
    name: 'foregroundWarningPrimaryHover',
    designName: 'Fg/Warning/Primary (hover)',
  );

  @override
  AppColor get foregroundWarningPrimaryPressed => AppColor._color(
    0xFF6F3900,
    name: 'foregroundWarningPrimaryPressed',
    designName: 'Fg/Warning/Primary (pressed)',
  );

  @override
  AppColor get foregroundWarningQuaternary => AppColor._color(
    0xFFE2CBB3,
    name: 'foregroundWarningQuaternary',
    designName: 'Fg/Warning/Quaternary',
  );

  @override
  AppColor get foregroundWarningSecondary => AppColor._color(
    0xFFC59766,
    name: 'foregroundWarningSecondary',
    designName: 'Fg/Warning/Secondary',
  );

  @override
  AppColor get foregroundWarningSecondaryHover => AppColor._color(
    0xFFB17533,
    name: 'foregroundWarningSecondaryHover',
    designName: 'Fg/Warning/Secondary (hover)',
  );

  @override
  AppColor get foregroundWarningSecondaryPressed => AppColor._color(
    0xFF9E5200,
    name: 'foregroundWarningSecondaryPressed',
    designName: 'Fg/Warning/Secondary (pressed)',
  );

  @override
  AppColor get foregroundWarningTertiary => AppColor._color(
    0xFFD8BA99,
    name: 'foregroundWarningTertiary',
    designName: 'Fg/Warning/Tertiary',
  );
}
